import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';

dotenv.config();

const User = mongoose.model('User', new mongoose.Schema({
  email: String,
  password: String,
  name: String,
  role: String,
  phone: String,
  location: String,
  isVerified: Boolean,
  isActive: Boolean,
  createdAt: Date,
  updatedAt: Date,
}));

const Contractor = mongoose.model('Contractor', new mongoose.Schema({
  userId: mongoose.Types.ObjectId,
  company: String,
  specialties: [String],
  bio: String,
  experience: Number,
  rating: Number,
  totalProjects: Number,
  completionRate: Number,
  portfolio: Array,
  certifications: Array,
  availability: String,
  hourlyRate: Number,
  isVerified: Boolean,
  isActive: Boolean,
  createdAt: Date,
  updatedAt: Date,
}));

const seedContractors = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || '');
    console.log('✅ Connected to MongoDB');

    // Create 20 Contractor Users with Indian details (Additional contractors)
    const contractorUsers = [
      {
        email: 'rajkumar.construction@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Raj Kumar',
        role: 'contractor',
        phone: '+91 8765432100',
        location: 'Mumbai, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'priyadesign.arch@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Priya Design',
        role: 'contractor',
        phone: '+91 8765432101',
        location: 'Bangalore, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'amit.struct.eng@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Amit Engineer',
        role: 'contractor',
        phone: '+91 8765432102',
        location: 'Delhi, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'kavya.design.pro@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Kavya Designer',
        role: 'contractor',
        phone: '+91 8765432103',
        location: 'Pune, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'vikram.power.tech@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Vikram Tech',
        role: 'contractor',
        phone: '+91 8765432104',
        location: 'Hyderabad, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'ananya.plumb.pro@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Ananya Pro',
        role: 'contractor',
        phone: '+91 8765432105',
        location: 'Chennai, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'rohan.art.works@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Rohan Works',
        role: 'contractor',
        phone: '+91 8765432106',
        location: 'Ahmedabad, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'neha.wooden.craft@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Neha Craft',
        role: 'contractor',
        phone: '+91 8765432107',
        location: 'Jaipur, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'suresh.build.pro@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Suresh Builder',
        role: 'contractor',
        phone: '+91 8765432108',
        location: 'Kolkata, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'divya.green.space@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Divya Green',
        role: 'contractor',
        phone: '+91 8765432109',
        location: 'Kochi, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'harsh.roof.expert@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Harsh Expert',
        role: 'contractor',
        phone: '+91 8765432110',
        location: 'Lucknow, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'meera.tile.master@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Meera Master',
        role: 'contractor',
        phone: '+91 8765432111',
        location: 'Surat, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'yogesh.cool.sys@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Yogesh System',
        role: 'contractor',
        phone: '+91 8765432112',
        location: 'Vadodara, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'pooja.floor.pro@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Pooja Pro',
        role: 'contractor',
        phone: '+91 8765432113',
        location: 'Chandigarh, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'sameer.found.expert@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Sameer Expert',
        role: 'contractor',
        phone: '+91 8765432114',
        location: 'Bhopal, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'ritika.glass.pro@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Ritika Pro',
        role: 'contractor',
        phone: '+91 8765432115',
        location: 'Indore, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'arjun.cement.pro@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Arjun Pro',
        role: 'contractor',
        phone: '+91 8765432116',
        location: 'Nagpur, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'swati.demo.expert@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Swati Expert',
        role: 'contractor',
        phone: '+91 8765432117',
        location: 'Pune, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'nitin.earth.move@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Nitin Move',
        role: 'contractor',
        phone: '+91 8765432118',
        location: 'Varanasi, India',
        isVerified: true,
        isActive: true,
      },
      {
        email: 'sneha.finish.art@gmail.com',
        password: await bcrypt.hash('password123', 10),
        name: 'Sneha Art',
        role: 'contractor',
        phone: '+91 8765432119',
        location: 'Noida, India',
        isVerified: true,
        isActive: true,
      },
    ];

    const insertedUsers = await User.insertMany(contractorUsers);
    console.log('✅ Created 20 contractor users');

    // Create Contractor Profiles with diverse specialties
    const contractorProfiles = [
      {
        userId: insertedUsers[0]._id,
        company: 'Raj Construction Group',
        specialties: ['Residential Construction', 'Project Management', 'Civil Engineering'],
        bio: 'Premier construction company with 12+ years in premium residential projects',
        experience: 12,
        rating: 4.8,
        totalProjects: 45,
        completionRate: 98,
        availability: 'available',
        hourlyRate: 1500,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[1]._id,
        company: 'Priya Design Studio',
        specialties: ['Architecture', 'Interior Design', 'Urban Planning'],
        bio: 'Award-winning design studio creating modern and sustainable spaces',
        experience: 10,
        rating: 4.9,
        totalProjects: 38,
        completionRate: 100,
        availability: 'busy',
        hourlyRate: 2000,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[2]._id,
        company: 'Amit Struct Engineers',
        specialties: ['Civil Engineering', 'Foundation Works', 'Structural Design'],
        bio: 'Specialized structural engineering with focus on sustainable projects',
        experience: 15,
        rating: 4.7,
        totalProjects: 52,
        completionRate: 96,
        availability: 'available',
        hourlyRate: 1800,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[3]._id,
        company: 'Kavya Design Hub',
        specialties: ['Interior Design', 'Space Planning', 'Luxury Finishes'],
        bio: 'Creating beautiful and functional spaces for homes and offices',
        experience: 8,
        rating: 4.6,
        totalProjects: 28,
        completionRate: 97,
        availability: 'available',
        hourlyRate: 1200,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[4]._id,
        company: 'Vikram Power Systems',
        specialties: ['Electrical Works', 'Smart Home Systems', 'Power Distribution'],
        bio: 'Modern electrical solutions with smart automation and renewable energy',
        experience: 11,
        rating: 4.5,
        totalProjects: 40,
        completionRate: 95,
        availability: 'available',
        hourlyRate: 1400,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[5]._id,
        company: 'Ananya Plumbing Pro',
        specialties: ['Plumbing', 'Water Systems', 'Pipe Installation'],
        bio: 'Professional plumbing with 9 years of residential and commercial expertise',
        experience: 9,
        rating: 4.4,
        totalProjects: 35,
        completionRate: 94,
        availability: 'available',
        hourlyRate: 900,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[6]._id,
        company: 'Rohan Art Finishes',
        specialties: ['Painting', 'Wall Finishing', 'Waterproofing'],
        bio: 'Expert in premium finishes and weather-resistant painting solutions',
        experience: 7,
        rating: 4.3,
        totalProjects: 42,
        completionRate: 93,
        availability: 'available',
        hourlyRate: 800,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[7]._id,
        company: 'Neha Wooden Crafts',
        specialties: ['Carpentry', 'Wooden Works', 'Furniture Making'],
        bio: 'Master carpenter specializing in bespoke wooden designs',
        experience: 10,
        rating: 4.7,
        totalProjects: 38,
        completionRate: 97,
        availability: 'available',
        hourlyRate: 1100,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[8]._id,
        company: 'Suresh Build Masters',
        specialties: ['Masonry Work', 'Brickwork', 'Concrete Casting'],
        bio: 'Expert in masonry with attention to structural integrity and quality',
        experience: 13,
        rating: 4.6,
        totalProjects: 55,
        completionRate: 96,
        availability: 'busy',
        hourlyRate: 950,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[9]._id,
        company: 'Divya Green Spaces',
        specialties: ['Landscaping', 'Garden Design', 'Outdoor Construction'],
        bio: 'Creating beautiful outdoor spaces with sustainable practices',
        experience: 8,
        rating: 4.5,
        totalProjects: 32,
        completionRate: 95,
        availability: 'available',
        hourlyRate: 1000,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[10]._id,
        company: 'Harsh Roofing Experts',
        specialties: ['Roofing', 'Waterproofing', 'Flat Roof Installation'],
        bio: 'Professional roofing services with premium quality materials',
        experience: 11,
        rating: 4.4,
        totalProjects: 40,
        completionRate: 94,
        availability: 'available',
        hourlyRate: 1050,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[11]._id,
        company: 'Meera Tile Masters',
        specialties: ['Tiling', 'Ceramic Installation', 'Marble Works'],
        bio: 'Expert tile installation with premium materials and aesthetics',
        experience: 9,
        rating: 4.6,
        totalProjects: 36,
        completionRate: 97,
        availability: 'available',
        hourlyRate: 1150,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[12]._id,
        company: 'Yogesh Cool Systems',
        specialties: ['HVAC Systems', 'Air Conditioning', 'Ventilation'],
        bio: 'Professional HVAC with energy-efficient solutions',
        experience: 10,
        rating: 4.7,
        totalProjects: 39,
        completionRate: 98,
        availability: 'available',
        hourlyRate: 1600,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[13]._id,
        company: 'Pooja Flooring Pro',
        specialties: ['Flooring', 'Marble Installation', 'Wooden Flooring'],
        bio: 'Premium flooring solutions with expert installation',
        experience: 8,
        rating: 4.5,
        totalProjects: 31,
        completionRate: 96,
        availability: 'available',
        hourlyRate: 1200,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[14]._id,
        company: 'Sameer Found Experts',
        specialties: ['Foundation Works', 'Pile driving', 'Soil Testing'],
        bio: 'Expert in deep foundation works and structural ground preparation',
        experience: 14,
        rating: 4.8,
        totalProjects: 48,
        completionRate: 97,
        availability: 'busy',
        hourlyRate: 1800,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[15]._id,
        company: 'Ritika Glass & Aluminum',
        specialties: ['Glass Works', 'Aluminum Fabrication', 'Window Installation'],
        bio: 'Custom glass and aluminum solutions for all projects',
        experience: 9,
        rating: 4.4,
        totalProjects: 34,
        completionRate: 95,
        availability: 'available',
        hourlyRate: 1050,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[16]._id,
        company: 'Arjun Concrete Pro',
        specialties: ['Concrete Works', 'Ready Mix Concrete', 'Concrete Repairs'],
        bio: 'High-quality concrete solutions with durability focus',
        experience: 12,
        rating: 4.6,
        totalProjects: 44,
        completionRate: 96,
        availability: 'available',
        hourlyRate: 1100,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[17]._id,
        company: 'Swati Demolition Pro',
        specialties: ['Demolition', 'Dismantling', 'Waste Management'],
        bio: 'Safe and efficient demolition with proper waste management',
        experience: 7,
        rating: 4.3,
        totalProjects: 25,
        completionRate: 94,
        availability: 'available',
        hourlyRate: 1300,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[18]._id,
        company: 'Nitin Earth Movers',
        specialties: ['Excavation', 'Earth Moving', 'Site Clearing'],
        bio: 'Heavy machinery operation and site preparation specialist',
        experience: 13,
        rating: 4.5,
        totalProjects: 41,
        completionRate: 95,
        availability: 'available',
        hourlyRate: 1250,
        isVerified: true,
        isActive: true,
      },
      {
        userId: insertedUsers[19]._id,
        company: 'Sneha Finishes Art',
        specialties: ['Interior Finishing', 'Polishing', 'Surface Treatment'],
        bio: 'Expert in final touches and premium surface finishes',
        experience: 8,
        rating: 4.4,
        totalProjects: 29,
        completionRate: 96,
        availability: 'available',
        hourlyRate: 950,
        isVerified: true,
        isActive: true,
      },
    ];

    await Contractor.insertMany(contractorProfiles);
    console.log('✅ Created 20 contractor profiles');

    console.log('\n📊 Contractor Data Summary:');
    console.log('   - 20 Contractor users from different Indian cities');
    console.log('   - Diverse specialties: Architecture, Civil, Electrical, Plumbing, Painting, Carpentry, etc.');
    console.log('   - All verified with high ratings (4.3-4.9 stars)');
    console.log('   - Experience range: 7-15 years');
    console.log('   - Hourly rates: ₹800 - ₹2000');
    console.log('   - Mix of availability: Available & Busy contractors');
    console.log('\n✨ Contractor seeding completed successfully!');

  } catch (error) {
    console.error('❌ Error seeding contractors:', error);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Database connection closed');
  }
};

seedContractors();
